# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_finger1_joint